(in-package :frelia-xml-test)

(plan 4)
(is (render-xml-element '(:test))
    "<test></test>")
(is (render-xml-element '(:test :foo "bar"))
    "<test foo=\"bar\"></test>")
(is (render-xml-element '(:test :foo "bar" "content a" :spam "eggs" "content b"))
    "<test foo=\"bar\" spam=\"eggs\">content acontent b</test>")
(is (render-xml-element '("test" (("foo-dash" . "bar")) "spam" "eggs"))
    "<test foo-dash=\"bar\">spameggs</test>")
(finalize)

(plan 2)
(is (render-xml '() '(:test))
    "<?xml?><test></test>")
(is (render-xml '(("version" . "777")) '(:test))
    "<?xml version=\"777\"?><test></test>")
(finalize)
