runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: www/index.html
  upload: www/index.html

- url: /css/(.*)
  static_files: www/\1
  upload: www/css/(.*)

- url: /img/(.*)
  static_files: www/\1
  upload: www/img/(.*)

- url: /files/(.*)
  static_files: www/\1
  upload: www/files/(.*)

- url: /(.*)
  static_files: www/\1.html
  upload: www/(.*)
