runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: yaml
  version: "3.10"
- name: flask
  version: "0.12"

handlers:
- url: /(css|img|files)/(.*)
  static_files: static/\1/\2
  upload: static/(css|img|files)/(.*)

- url: /(.*\.txt)
  static_files: static/\1
  upload: static/(.*\.txt)

- url: /.*
  script: app.app.app
