// Code generated by "binpack -name indexTemplate index.html"; DO NOT EDIT.

package templates

const indexTemplate = "title: Feles Atra\n---\n<p>This is my homepage.  There are many like it, but this one is mine.</p>\n\n<p>This page is <code>index.html</code>.  Therefore, the site index can be found here.</p>\n\n<ul>\n  {{- range .Pages}}\n  <li><a href=\"{{.Path}}\">{{.Title}}</a></li>\n  {{- end}}\n<ul>\n"
