// Code generated by "binpack -name sitemapTemplate sitemap.xml"; DO NOT EDIT.

package templates

const sitemapTemplate = "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<urlset xmlns=\"http://www.sitemaps.org/schemas/sitemap/0.9\"\n        xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\n        xsi:schemaLocation=\"http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd\">\n  {{- range .}}\n  <url>\n    {{- if .Loc}}\n    <loc>{{.Loc}}</loc>\n    {{- end}}\n    {{- if .LastMod}}\n    <lastmod>{{.LastMod}}</lastmod>\n    {{- end}}\n    {{- if .ChangeFreq}}\n    <changefreq>{{.ChangeFreq}}</changefreq>\n    {{- end}}\n    {{- if .Priority}}\n    <priority>{{.Priority}}</priority>\n    {{- end}}\n  </url>\n  {{- end}}\n</urlset>\n"
