runtime: go
api_version: go1.8

handlers:
- url: /(css|img|files)/(.*)
  static_files: static/\1/\2
  upload: static/(css|img|files)/(.*)
  secure: always

- url: /(.*\.txt)
  static_files: static/\1
  upload: static/(.*\.txt)
  secure: always

- url: /(sitemap\.xml)
  static_files: \1
  upload: (sitemap\.xml)
  secure: always

- url: /.*
  script: _go_app
  secure: always
