runtime: go112

handlers:
- url: /css
  static_dir: www/static/css
  secure: always

- url: /img
  static_dir: www/static/img
  secure: always

- url: /files
  static_dir: www/static/files
  secure: always

- url: /(.*\.txt)
  static_files: www/static/\1
  upload: www/static/(.*\.txt)
  secure: always

- url: /(sitemap\.xml)
  static_files: www/\1
  upload: www/(sitemap\.xml)
  secure: always

- url: /.*
  script: auto
  secure: always
